### ISSUE TITLE
Buttons don't get disabled

### ISSUE THREAD

**Issue by fleaz** [fleaz/timetrackr#12]
In my old version the pause button was only clickable when the timer was running, the play button was only clickable when the timer was stopped and the reset button was only clickable when the timer has been started at least once. This feature is gone since the optimization in 55d6a6979ba8ce7c4f40877874bc7491179a104d

@kuroidoruido would you take a look at this? :)

**Comment by kuroidoruido** [comment]
Sure! I think I broke something, sorry! I check this tonight!
